---
- name: Install OpenPBS
  hosts: all
  become: true
  vars:
    pbs_prefix: /opt/pbs

  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - gcc
        - make
        - libtool
        - libhwloc-dev
        - libx11-dev
        - libxt-dev
        - libedit-dev
        - libical-dev
        - ncurses-dev
        - perl
        - postgresql-server-dev-all
        - postgresql-contrib
        - python3-dev
        - tcl-dev
        - tk-dev
        - swig
        - libexpat-dev
        - libssl-dev
        - libxext-dev
        - libxft-dev
        - autoconf
        - automake
        - g++
        - libcjson-dev
      changed_when: false

    - name: Clone or pull OpenPBS repository
      git:
        repo: https://github.com/openpbs/openpbs.git
        dest: "~/openpbs"
        version: master
        update: yes

    - name: Run autoconfigure script
      shell: "./autogen.sh"
      args:
        chdir: "~/openpbs"

    - name: Configure OpenPBS
      shell: "./configure --prefix={{ pbs_prefix }} --enable-ptl"
      args:
        chdir: "~/openpbs"

    - name: Build OpenPBS
      make:
        chdir: "~/openpbs"

    - name: Install OpenPBS
      make:
        chdir: "~/openpbs"
        target: install

    - name: Run post-install script
      shell: "{{ pbs_prefix }}/libexec/pbs_postinstall"

    - name: Update /etc/pbs.conf
      lineinfile:
        path: /etc/pbs.conf
        regexp: '^PBS_SERVER='
        line: 'PBS_SERVER=host'

    - name: Modify file permissions for SUID privilege
      file:
        path: "{{ pbs_prefix }}/sbin/{{ item }}"
        mode: '4755'
      loop:
        - pbs_iff
        - pbs_rcp

    - name: Start OpenPBS services
      shell: "{{ pbs_prefix }}/init.d/pbs start"
