---
- name: Install OpenPBS
  hosts: myservers
  become: true
  vars:
    pbs_prefix: /opt/pbs
    pbs_repo_dir: /home/ansible_usr/openpbs
    pbs_server_ip: 192.168.122.200

  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - gcc
        - make
        - libtool
        - libhwloc-dev
        - libx11-dev
        - libxt-dev
        - libedit-dev
        - libical-dev
        - ncurses-dev
        - perl
        - postgresql-server-dev-all
        - postgresql-contrib
        - python3-dev
        - tcl-dev
        - tk-dev
        - swig
        - libexpat-dev
        - libssl-dev
        - libxext-dev
        - libxft-dev
        - autoconf
        - automake
        - g++
        - libcjson-dev
      changed_when: false

    - name: Clone or pull OpenPBS repository
      git:
        repo: https://github.com/openpbs/openpbs.git
        dest: "{{ pbs_repo_dir }}"
        version: master
        update: yes

    - name: Run autoconfigure script
      shell: "./autogen.sh"
      args:
        chdir: "{{ pbs_repo_dir }}"

    - name: Configure OpenPBS
      shell: "./configure --prefix={{ pbs_prefix }} --enable-ptl"
      args:
        chdir: "{{ pbs_repo_dir }}"

    - name: Build OpenPBS
      make:
        chdir: "{{ pbs_repo_dir }}"

    - name: Install OpenPBS
      make:
        chdir: "{{ pbs_repo_dir }}"
        target: install

    - name: Run post-install script
      shell: "{{ pbs_prefix }}/libexec/pbs_postinstall"

    - name: Update /etc/pbs.conf
      lineinfile:
        path: /etc/pbs.conf
        regexp: '^PBS_SERVER='
        line: 'PBS_SERVER=host'

    - name: Modify file permissions for SUID privilege
      file:
        path: "{{ pbs_prefix }}/sbin/{{ item }}"
        mode: '4755'
      loop:
        - pbs_iff
        - pbs_rcp

    - name: Update /etc/pbs.conf
      lineinfile:
        path: /etc/pbs.conf
        regexp: '^PBS_SERVER='
        line: 'PBS_SERVER={{ pbs_server_ip }}'
      notify: Restart PBS

    - name: Update PBS_START_SERVER
      lineinfile:
        path: /etc/pbs.conf
        regexp: '^PBS_START_SERVER='
        line: 'PBS_START_SERVER=0'
      notify: Restart PBS

    - name: Update PBS_START_SCHED
      lineinfile:
        path: /etc/pbs.conf
        regexp: '^PBS_START_SCHED='
        line: 'PBS_START_SCHED=0'
      notify: Restart PBS

    - name: Update PBS_START_COMM
      lineinfile:
        path: /etc/pbs.conf
        regexp: '^PBS_START_COMM='
        line: 'PBS_START_COMM=0'
      notify: Restart PBS

    - name: Update PBS_START_MOM
      lineinfile:
        path: /etc/pbs.conf
        regexp: '^PBS_START_MOM='
        line: 'PBS_START_MOM=0'
      notify: Restart PBS

    - name: Start OpenPBS services
      shell: "/etc/init.d/pbs start"

    - name: Source PBS profile
      shell: ". /etc/profile.d/pbs.sh"
